name: Plus
main: com.marcusslover.plus.PlusPlugin
version: 4.3.0-SNAPSHOT
description: "A set of tools used for programming Minecraft plugins."
website: "https://github.com/MarcusSlover/Plus"
api-version: 1.21.1
author: MarcusSlover