name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - master
      - main
      - '4.0'
      - 'release/**'
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up Temurin JDK 21 and enable Gradle cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # 3. Make Gradle wrapper executable (Linux runners)
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      # 4. Build
      - name: Build with Gradle
        run: ./gradlew build
